<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-19T20:47:30 IST" name="Suite" finished-at="2022-07-19T20:48:24 IST" duration-ms="54107">
    <groups>
      <group name="sanity">
        <method signature="DemoLoginTest.validateInvalidPasswordErrorMessage()[pri:2, instance:com.demo.tests.DemoLoginTest@209da20d]" name="validateInvalidPasswordErrorMessage" class="com.demo.tests.DemoLoginTest"/>
        <method signature="DemoLoginTest.validateInvalidUsernameErrorMessage()[pri:1, instance:com.demo.tests.DemoLoginTest@209da20d]" name="validateInvalidUsernameErrorMessage" class="com.demo.tests.DemoLoginTest"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2022-07-19T20:47:30 IST" name="ChromeTest" finished-at="2022-07-19T20:48:24 IST" duration-ms="54107">
      <class name="com.demo.tests.DemoLoginTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.demo.tests.DemoLoginTest@209da20d]" started-at="2022-07-19T20:47:31 IST" name="setup" finished-at="2022-07-19T20:48:17 IST" duration-ms="46164" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateInvalidUsernameErrorMessage()[pri:1, instance:com.demo.tests.DemoLoginTest@209da20d]" started-at="2022-07-19T20:48:17 IST" name="validateInvalidUsernameErrorMessage" finished-at="2022-07-19T20:48:18 IST" duration-ms="406" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[checkElementDisplayed (ValidationActionHelper) : no such element: Unable to locate element: {"method":"xpath","selector":"//h3[text()='Epic sadface: Username is required']"}
  (Session info: chrome=103.0.5060.114)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.4', revision: '535d840ee2'
System info: host: 'RVSKCH542LT', ip: '192.168.255.223', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ce275134d189d4bcf80b52497adce9e, findElement {using=xpath, value=//h3[text()='Epic sadface: Username is required']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.114, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: C:\Users\HP\AppData\Local\T...}, goog:chromeOptions: {debuggerAddress: localhost:60858}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:60858/devtoo..., se:cdpVersion: 103.0.5060.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 3ce275134d189d4bcf80b52497adce9e]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: checkElementDisplayed (ValidationActionHelper) : no such element: Unable to locate element: {"method":"xpath","selector":"//h3[text()='Epic sadface: Username is required']"}
  (Session info: chrome=103.0.5060.114)
For documentation on this error, please visit: https://selenium.dev/exceptions/#no_such_element
Build info: version: '4.1.4', revision: '535d840ee2'
System info: host: 'RVSKCH542LT', ip: '192.168.255.223', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.1'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [3ce275134d189d4bcf80b52497adce9e, findElement {using=xpath, value=//h3[text()='Epic sadface: Username is required']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.114, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: C:\Users\HP\AppData\Local\T...}, goog:chromeOptions: {debuggerAddress: localhost:60858}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:60858/devtoo..., se:cdpVersion: 103.0.5060.114, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 3ce275134d189d4bcf80b52497adce9e
at com.obs.actions.ValidationActionHelpers.isElementVisible(ValidationActionHelpers.java:19)
at com.demo.tests.DemoLoginTest.validateInvalidUsernameErrorMessage(DemoLoginTest.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateInvalidUsernameErrorMessage -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.demo.tests.DemoLoginTest@209da20d]" started-at="2022-07-19T20:48:18 IST" name="quitBrowser" finished-at="2022-07-19T20:48:18 IST" duration-ms="382" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.demo.tests.DemoLoginTest@209da20d]" started-at="2022-07-19T20:48:18 IST" name="setup" finished-at="2022-07-19T20:48:24 IST" duration-ms="5821" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <exception class="com.obs.exception.AutomationException">
            <message>
              <![CDATA[Cannot navigate to invalid URL, please specify valid URL]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.obs.exception.AutomationException: Cannot navigate to invalid URL, please specify valid URL
at com.obs.base.AutomationBase.launchChromeBrowser(AutomationBase.java:47)
at com.obs.base.AutomationBase.launchBrowser(AutomationBase.java:23)
at com.demo.tests.DemoLoginTest.setup(DemoLoginTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.obs.exception.AutomationException: Cannot navigate to invalid URL, please specify valid URL
at com.obs.actions.WebActionHelpers.navigateToBrowser(WebActionHelpers.java:27)
at com.obs.base.AutomationBase.launchChromeBrowser(AutomationBase.java:43)
... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- com.obs.exception.AutomationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="validateInvalidPasswordErrorMessage()[pri:2, instance:com.demo.tests.DemoLoginTest@209da20d]" started-at="2022-07-19T20:48:24 IST" name="validateInvalidPasswordErrorMessage" finished-at="2022-07-19T20:48:24 IST" duration-ms="0" status="SKIP">
          <exception class="com.obs.exception.AutomationException">
            <message>
              <![CDATA[Cannot navigate to invalid URL, please specify valid URL]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.obs.exception.AutomationException: Cannot navigate to invalid URL, please specify valid URL
at com.obs.base.AutomationBase.launchChromeBrowser(AutomationBase.java:47)
at com.obs.base.AutomationBase.launchBrowser(AutomationBase.java:23)
at com.demo.tests.DemoLoginTest.setup(DemoLoginTest.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:527)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.obs.exception.AutomationException: Cannot navigate to invalid URL, please specify valid URL
at com.obs.actions.WebActionHelpers.navigateToBrowser(WebActionHelpers.java:27)
at com.obs.base.AutomationBase.launchChromeBrowser(AutomationBase.java:43)
... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- com.obs.exception.AutomationException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateInvalidPasswordErrorMessage -->
        <test-method is-config="true" signature="quitBrowser()[pri:0, instance:com.demo.tests.DemoLoginTest@209da20d]" started-at="2022-07-19T20:48:24 IST" name="quitBrowser" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1658243904711" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- com.demo.tests.DemoLoginTest -->
    </test> <!-- ChromeTest -->
  </suite> <!-- Suite -->
</testng-results>
